-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL 

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
SET @@auto_increment_increment=1;

-- -----------------------------------------------------
-- Schema 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movie-magic` DEFAULT CHARACTER SET utf8 ;
USE `movie-magic` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie-magic`.`users` (
  `userID` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(20) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `movie-magic`.`reviews`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie-magic`.`reviews` (
  `Favorite_Movie` VARCHAR (20) NOT NULL,
  `2nd_Favorite_Movie` VARCHAR (20) NOT NULL,
  `3rd_Favorite_Movies` VARCHAR (20) NOT NULL,
  `Favorite_Actor` VARCHAR(20) NOT NULL,
   `2nd_Favorite_Actor` VARCHAR(20) NOT NULL,
    `3rd_Favorite_Actor` VARCHAR(20) NOT NULL,
  `review` TEXT(255) NOT NULL,
  PRIMARY KEY (`reviewID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movie-magic`.`movies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movie-magic`.`movies` (
  `movieID` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(20) NOT NULL,
  `rating` VARCHAR(20) NOT NULL,
  `year` INT(11) NOT NULL,
  `watched` VARCHAR(1) NOT NULL,
  `TMDB_ID` INT(11) NOT NULL,
  `userID` INT(11),
  `reviewID` INT(11),
  PRIMARY KEY (`movieID`),
  FOREIGN KEY (`userID`) REFERENCES `users`(`userID`),
  FOREIGN KEY (`reviewID`) REFERENCES `reviews`(`reviewID`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO users (userID, username, password, email) VALUES ("password", "username", "email@mail.com") ;
INSERT INTO reviews (reviewID, review_title, rating, review, userID, movieID) VALUES (1, "test review", 6, "Test", 1, 1);


-- ALTER TABLE movies add TMDB_ID int NOT NULL;
-- DELETE FROM reviews WHERE reviewID = 11;
DELETE FROM movies WHERE movieID = 0;



INSERT INTO movies (title, genre, rating, year, watched, TMDB_ID, userID)
	VALUES (
		"Spirited Away", "UNIMPLEMENTED", 8.4, 2001, 1, 129,
		(SELECT userID FROM users WHERE userID = 1)
    );

 INSERT INTO movies (title, genre, rating, year, watched, TMDB_ID) VALUES ("Spirited Away", "UNIMPLEMENTED", 8.4, 2001, 1, 129 );
   
    
SELECT * FROM users ORDER BY userID DESC;
SELECT * FROM reviews ORDER BY reviewID DESC;
SELECT * FROM movies ORDER BY movieID DESC;


SET FOREIGN_KEY_CHECKS = 0;
drop table if exists users;
drop table if exists movies;
drop table if exists reviews;
SET FOREIGN_KEY_CHECKS = 1;
